# PlayerList Configuration File

PlayerList:
  global-players:
    one-player: '&9There is &c%players &9player online.'
    more-players: '&9There are &c%players &9players online.'
  use-displayname: true
  show-on-same-line: true
  ranks:
    Admin:
      color: '&4'
      admin: '&4'
    Moderator:
      color: '&3'
      moderator: '&3'
    Architect:
      color: '&a'
      architect: '&a'
    Trusted:
      color: '&6'
      trusted: '&6'
    Default:
      color: '&7'
      default: '&7'
    Donator:
      color: '&e'
      ddefault: '&7'
      dtrusted: '&6'
      darchitect: '&a'
      dmoderator: '&3'