# PlayerList Configuration File

PlayerList:
  global-players:
    one-player: '&9There is &c%players &9player online.'
    more-players: '&9There are &c%players &9players online.'
  ranks:
    Admin:
      admin: '&4'
    Moderator:
      moderator: '&3'
    Architect:
      architect: '&a'
    Trusted:
      trusted: '&6'
    Default:
      default: '&7'
    Donator:
      ddefault: '&7'
      dtrusted: '&6'
      darchitect: '&a'
      dmoderator: '&3'