name: PlayerList
main: org.Dragonphase.PlayerList.PlayerList
version: 1.0
description: >
             PlayerList lets you show all players in the server separated by ranks. You may also set colors for defined ranks
commands:
  playerlist:
    description: WorldPlayerList command
  list:
    description: Show online players in all worlds
  plist:
    description: Show online players in all worlds
  playerist:
    description: Show online players in all worlds